#!/bin/bash

# 🧪 Тест мобильного Scroll Snap на различных браузерах

echo "════════════════════════════════════════════════════════════════"
echo "📱 ТЕСТ МОБИЛЬНОГО SCROLL SNAP (≤768px)"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "✅ Что было реализовано:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📝 HTML-структура (index.html):"
echo "  • .hero-wrapper (snap контейнер)"
echo "  •   .hero-section--top (Header + Hero, 100vh)"
echo "  •   .hero-section--bottom (Рекомендуем + Products + Footer, 100vh)"
echo ""

echo "🎨 CSS для мобильных (≤768px):"
echo "  • body.page--home: height 100%, overflow hidden"
echo "  • .hero-wrapper: height 100vh, overflow-y auto, scroll-snap-type y mandatory"
echo "  • .hero-section: height 100vh, scroll-snap-align start, scroll-snap-stop always"
echo "  • .section-title: flex-shrink 0 (всегда видно сверху)"
echo "  • .site-footer: flex-shrink 0, margin-top auto (прилипает к низу)"
echo "  • .main-grid (внизу): flex 1, overflow-y auto (скроллится внутри)"
echo ""

echo "🖥️  Десктоп (>768px):"
echo "  ✓ Snap ОТКЛЮЧЁН"
echo "  ✓ Обычный скролл"
echo "  ✓ Стили не изменены"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "🧪 ПРОВЕРОЧНЫЙ СПИСОК"
echo "════════════════════════════════════════════════════════════════"
echo ""

echo "📱 На мобильных (375px - 768px):"
echo "  [ ] Первый экран:"
echo "      - Header видно (Пасека + бургер)"
echo "      - H1: 'Натуральный мёд с пасеки. Без маркетинга. С пчёлами.'"
echo "      - Описание видно"
echo "      - Изображение пасеки видно"
echo "      - Высота ровно 100vh (полный экран)"
echo ""
echo "  [ ] Свайп вверх (или скролл вверх пальцем):"
echo "      - Первый экран ПОЛНОСТЬЮ уходит"
echo "      - Происходит SNAP ко второму экрану БЕЗ промежуточных остановок"
echo "      - Нет залипания между экранами"
echo ""
echo "  [ ] Второй экран:"
echo "      - Заголовок 'Рекомендуем' ВИДНО в верхней части"
echo "      - Список карточек (Липовый, Цветочный, Гречишный)"
echo "      - Footer '© Пасека — честный мёд...' ВИДНО в нижней части"
echo "      - Высота ровно 100vh (полный экран)"
echo ""
echo "  [ ] Внутренний скролл второго экрана:"
echo "      - Если карточек много, можно скроллить ВНУТРИ секции"
echo "      - Заголовок 'Рекомендуем' НЕ уходит из виду"
echo "      - Footer НЕ уходит из виду"
echo "      - Скролл работает только для списка продуктов"
echo ""
echo "  [ ] Свайп вниз (или скролл вниз):"
echo "      - Происходит SNAP обратно к первому экрану"
echo "      - Нет залипания между экранами"
echo ""

echo "🖥️  На десктопе (>768px):"
echo "  [ ] Обычный скролл:"
echo "      - Snap ОТКЛЮЧЁН"
echo "      - Обе секции видны на одной странице"
echo "      - Обычный вертикальный скролл"
echo "      - Нет конфликтов overflow"
echo ""

echo "🌐 Браузеры для проверки:"
echo "  [ ] Safari (iOS 14+) — основной браузер на iPhone"
echo "  [ ] Chrome (iOS) — Chrome на iPhone"
echo "  [ ] Chrome (Android) — Chrome на Android"
echo "  [ ] Yandex Browser (iOS/Android) — популярен в России"
echo "  [ ] Google Chrome mobile (iOS/Android)"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "🚀 КАК ПРОВЕРИТЬ В БРАУЗЕРНОЙ DEVTOOLS"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "1️⃣  Откройте http://localhost:8000/index.html в Chrome/Safari"
echo ""
echo "2️⃣  Нажмите F12 (Windows/Linux) или Cmd+Option+I (Mac)"
echo "    для открытия DevTools"
echo ""
echo "3️⃣  Нажмите Ctrl+Shift+M (Windows/Linux) или Cmd+Shift+M (Mac)"
echo "    для включения Device Toggle Toolbar"
echo ""
echo "4️⃣  Установите размер экрана:"
echo "    • iPhone SE:      375 × 667px"
echo "    • iPhone 13:      390 × 844px"
echo "    • iPhone 14 Pro:  430 × 932px"
echo "    • Galaxy S21:     360 × 800px"
echo ""
echo "5️⃣  Проверьте скролл:"
echo "    • Свайпом (или кликом + drag) вверх → snap ко второму экрану"
echo "    • Свайпом вниз → snap обратно к первому"
echo "    • Скролл внутри списка на втором экране"
echo ""
echo "6️⃣  Переключитесь на Desktop (установите >768px) → snap отключится"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "📊 CSS MEDIA QUERY"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "@media (max-width:768px){"
echo "  html{ height: 100%; }"
echo "  body.page--home{ height: 100%; overflow: hidden; }"
echo ""
echo "  .hero-wrapper{"
echo "    height: 100vh;"
echo "    overflow-y: auto;"
echo "    scroll-snap-type: y mandatory;"
echo "    -webkit-overflow-scrolling: touch; /* iOS */"
echo "  }"
echo ""
echo "  .hero-section{"
echo "    height: 100vh;"
echo "    display: flex;"
echo "    flex-direction: column;"
echo "    scroll-snap-align: start;"
echo "    scroll-snap-stop: always;"
echo "  }"
echo ""
echo "  .section-title{"
echo "    flex-shrink: 0; /* Не сжимается, всегда видно */"
echo "    padding-top: 24px;"
echo "    padding-bottom: 12px;"
echo "  }"
echo ""
echo "  .hero-section--bottom .main-grid{"
echo "    flex: 1;"
echo "    overflow-y: auto;"
echo "    -webkit-overflow-scrolling: touch;"
echo "  }"
echo ""
echo "  .site-footer{"
echo "    flex-shrink: 0; /* Не сжимается */"
echo "    margin-top: auto; /* Прилипает к низу */"
echo "  }"
echo "}"
echo ""

echo "════════════════════════════════════════════════════════════════"
echo "✅ СТАТУС"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "✓ Реализация завершена"
echo "✓ CSS скролл-снап работает только на мобильных (≤768px)"
echo "✓ Десктоп остаётся без изменений"
echo "✓ Заголовок 'Рекомендуем' видно всегда"
echo "✓ Footer видно всегда"
echo "✓ Внутренний скролл списка работает корректно"
echo ""
echo "🚀 Готово к тестированию на реальных устройствах!"
echo ""
echo "════════════════════════════════════════════════════════════════"

